### ISSUE TITLE
defaults/main.yml: issue with the db password in defaults and not setup in the sample setup

### ISSUE THREAD

**Issue by ctaperts** [bashrc666/ansible-role-icinga2#1]
if you change the db password in the sample playbook icingaweb2 will not work.

need to add in
```
    icinga2_icingaweb2_database:
      name: "{{ icinga2_database.user }}"
      user: "{{ icinga2_database.user }}"
      password: "{{ icinga2_database.password }}"
      host: "{{ icinga2_database.host }}"
```
to the readme sample setup

Thanks!
